### PR TITLE
Issue-#257-Added Hover Effects for the cards

### LINKED ISSUE #257: Adding Hover Effect to Cards
Hey!
I am Pranavdhar. I hope to add hover effects to the cards of organization, blog, and project which makes it look more appealing. If you wish to add this feature consider assigning it to me.
Thanks

### PR DESCRIPTION
**Pull request by iampranavdhar**
### Fixes #257 
**Description** <br/>
I had made the changes in the CSS files for adding hover effects which makes the website appealing. I had read the contributing guidelines and made the PR in the same way as suggested.
Thanks.

### CODE REVIEW

**Comment by shashankmotruri** [comment]
> 
> ### Fixes #257
> 
> **Description**
> 
> I had made the changes in the CSS files for adding hover effects which makes the website appealing. I had read the contributing guidelines and made the PR in the same way as suggested.
> Thanks.

Please follow contributing guide and follow the specific type of commit messages that we use.

**Comment by iampranavdhar** [comment]
Had changed the commit issue name as per the contributing guidelines.
Thanks

**Comment by gauravdas014** [comment]
@iampranavdhar can you please attach a screenshot?

**Comment by iampranavdhar** [comment]
Yeah, Sure @gauravdas014 
Normal:
Normal
On Hover:
OnHover

Actually its a hoer effect it looks better when we see a video or experience it directly but as suggested I am posting the screenshots
Thanks.

**Pull request merged**
