### PR TITLE
added controller for new comment

### LINKED ISSUE #125: Add new comment to the forum post
Create controller function to add new comment in the forum post

### PR DESCRIPTION
**Pull request by joharikushagra**
### Fixes #125  

**Description** <br/>
Added routes and controller for new comment. Made small correction in project controller as well.

### CODE REVIEW

**Comment by gauravdas014** [comment]
Please resolve the merge conflicts

**Comment by gauravdas014** [comment]
For creating comment, pass the postId as a param and use it for adding a new comment. Tell if you need more details. See the schemas once so that you know how the comment and post is linked

**Comment by joharikushagra** [comment]
@gauravdas014  plz review the changes

**Comment by gauravdas014** [comment]
Looks fine to me! 👍

**Pull request merged**
