### PR TITLE
Update project

### LINKED ISSUE #114: Update project
Make a controller function to update a project

### PR DESCRIPTION
**Pull request by pratikbaid3**
### Fixes #114  

**Description** <br/>
Completed the controller function for updating a project and added the route for it

**Screenshots** <br/>
Screenshot 2020-10-14 at 10 17 57 PM

### CODE REVIEW

**Comment by gauravdas014** [comment]
Please include the updated project in the response

**Comment by gauravdas014** [comment]
Please resolve the conflicts

**Comment by pratikbaid3** [comment]
@gauravdas014 Done

**Pull request merged**
