### PR TITLE
added user signup

### LINKED ISSUE #12: User authentication : Sign up
Build a sign up system from scratch. We won't be using things like passport js. Use bcrypt js for hashing the things. You can work on this issue once the user schema is created.

### PR DESCRIPTION
**Pull request by joharikushagra**
Fixes #12 
**Adding user signup**

### CODE REVIEW

**Comment by gauravdas014** [comment]
Do not check each of the condition like if user exists using try catch. Instead use a global try catch for the whole controller function and use if else for the other condition checking.

**Comment by joharikushagra** [comment]
okay I will create a single try catch

**Comment by gauravdas014** [comment]
On catch use a 400 error message. And try removing the merge conflict.

**Comment by joharikushagra** [comment]
I don't know how to remove the conflict...

**Comment by gauravdas014** [comment]
why you have used _doc . Explain !!

**Comment by joharikushagra** [comment]
the newUser object contains the complete mongoose object with all the getter and setters and if you simply return that it would populate the response with irrelevant properties, but using the _doc will give the javascript object containing  only user schema details.

**Comment by gauravdas014** [comment]
Please attach api response screenshot

**Comment by joharikushagra** [comment]
Capturepostman
Response With _doc

Capture2postman
Response without _doc

**Comment by gauravdas014** [comment]
The response you are getting with _doc can also be generated without using it, anyways, whatever you have done is correct. I am merging it.

**Pull request merged**
