### PR TITLE
Blog card component

### PR DESCRIPTION
**Pull request by sonali-singh97**

### CODE REVIEW

**Review by salil-naik — CHANGES_REQUESTED** [review]
Hi. Use className (css). Class cannot be used as it is a reserved word in JavaScript.

Follow the BEM CSS Architecture naming conventions while writing CSS.

**Review by salil-naik — COMMENTED** [review]
Class name 'footer' should strictly be used for the footer of the website. The correct and matching name would be author__card. Inside it will come author__image, author__name and date.

The class name 'card-container' doesn't match its function. A container is something that contains everything and should be used in the outermost div in my opinion. But in your case, it justs acts as a wrapper with padding on all sides.

**Comment by sonali-singh97** [comment]
I have changed the class names. 
Please review it and suggest changes.

**Review by salil-naik — APPROVED** [review]
Good work.

**Pull request merged**
