### PR TITLE
Organization Approval Flow Completed

### LINKED ISSUE #307: Newly Created Organizations are needed to be approved by admins
On creation of new organization create two boolean fields ```approved``` and ```declined``` and set it to false.

Make all the required changes in order to create api for full verification process.

### PR DESCRIPTION
**Pull request by jhasuraj01**
### Fixes #307 

**Description** <br/>
- Set default values for approved and declined to false in Schema
- Parameter of Model.findById changed to string
- Do not allow change value of approved and declined with update org api

### CODE REVIEW

**Review by gauravdas014 — CHANGES_REQUESTED** [review]
use `===` and `!==` instead of `==` and `!=` wherever necessary.

**Review by gauravdas014 — CHANGES_REQUESTED** [review]
in `orgController` you have used `delete` keyboard. It will work here. But in some other parts of code, we have simply make the property on the object undfined. I think we should maintain consistency in code style. So use `req.body.approved = undefined` and `req.body.declined = undefined`

**Comment by gauravdas014** [comment]
@jhasuraj01 Please do one thing, if in some places of code camel casing is not used, then change the variable name to make sure it uses the camel casing. In some places `orgid` is used, let's use `orgId`. Similarly in all other places.

**Comment by jhasuraj01** [comment]
> in `orgController` you have used `delete` keyboard. It will work here. But in some other parts of code, we have simply make the property on the object undfined. I think we should maintain consistency in code style. So use `req.body.approved = undefined` and `req.body.declined = undefined`

I used delete keyword to avoid accidental overwrite of those fields, does settings it to undefined behave same?

**Comment by jhasuraj01** [comment]
> > in `orgController` you have used `delete` keyboard. It will work here. But in some other parts of code, we have simply make the property on the object undfined. I think we should maintain consistency in code style. So use `req.body.approved = undefined` and `req.body.declined = undefined`
> 
> I used delete keyword to avoid accidental overwrite of those fields, does setting it to undefined behave same?

image
@gauravdas014 please have a look

**Comment by jhasuraj01** [comment]
@gauravdas014 you can merge #310 and #313. I will push all the necessary changes here.

**Comment by gauravdas014** [comment]
> > > in `orgController` you have used `delete` keyboard. It will work here. But in some other parts of code, we have simply make the property on the object undfined. I think we should maintain consistency in code style. So use `req.body.approved = undefined` and `req.body.declined = undefined`
> > 
> > 
> > I used delete keyword to avoid accidental overwrite of those fields, does setting it to undefined behave same?
> 
> image
> @gauravdas014 please have a look

Seems it's better to leave as `delete`. Don't change, keep it delete only

**Comment by jhasuraj01** [comment]
@gauravdas014 I have made all the necessary changes please review

**Review by gauravdas014 — APPROVED** [review]

**Comment by gauravdas014** [comment]
@jhasuraj01 Great work with the API docs! 
Would you like to work on
(i) Writing tests for API
(ii) Integrate backend API to the React App

These are the major tasks left.

**Comment by jhasuraj01** [comment]
> @jhasuraj01 Great work with the API docs!
> Would you like to work on
> (i) Writing tests for API
> (ii) Integrate backend API to the React App
> 
> These are the major tasks left.

I would have to learn unit testing and basics of react before starting with the issue, I will update you soon

**Comment by gauravdas014** [comment]
> > @jhasuraj01 Great work with the API docs!
> > Would you like to work on
> > (i) Writing tests for API
> > (ii) Integrate backend API to the React App
> > These are the major tasks left.
> 
> I would have to learn unit testing and basics of react before starting with those issues, I will update you soon

Feel free to dm me in discord, if you need any help in learning

**Comment by jhasuraj01** [comment]
@gauravdas014 Thanks in advance 😄

**Pull request merged**
