### PR TITLE
Create edit forum post controller function

### PR DESCRIPTION
**Pull request by Jyoti-S-16**
### Fixes #278 

**Description** <br/>
1. Added post route for edit post in forum controlle in routes/forumRoutes file.
2. Added controller function for respective post route in controller/forumController file.

### CODE REVIEW

**Review by shashankmotruri — CHANGES_REQUESTED** [review]
@Jyoti-S-16 the values are not updated . try req.body.updateHeading for all this can solve the issue.

**Comment by Jyoti-S-16** [comment]
I have dine the changes as suggested by you and have committed those changes

**Comment by Jyoti-S-16** [comment]
I have done the changes suggested by you and committed it

**Comment by shashankmotruri** [comment]
@gauravdas014 everything looks fine.

**Comment by gauravdas014** [comment]
@Jyoti-S-16 Please follow the contributing guidelines for the type of commit messages we are allowing.

**Comment by gauravdas014** [comment]
@Jyoti-S-16 Add a third argument in the `findByIdAndUpdate` which is 
```javascript
{
  new: true,
  runValidators: true,
}
```
that will make sure that the validators are not failing in updation

**Comment by Jyoti-S-16** [comment]
Ok I will do it by tomorrow  and I will take care of commit also.

**Comment by Jyoti-S-16** [comment]
I have added that argument to function findByIdAndUpdate and committed it.

**Comment by gauravdas014** [comment]
@Jyoti-S-16 I am editing the commit message this time, but from the next PR please follow the contributing guidelines for the type of commit messages we allow.

**Pull request merged**
