### PR TITLE
Typo Fix in Registration Page

### LINKED ISSUE #331: Typo in Registration Page
Capture

Please assign me this issue

File location:  feminist-bible-phase-2\frontend\src\pages\Registration\Registration.jsx

### PR DESCRIPTION
**Pull request by sreeharianilkumar1**
### Fixes #331 

**Description** <br/>
Typo fixed in registration page

**Screenshots** <br/>
Capture1

**Addition Information (if any)** <br/>
Mention any additional information that has been taken note of while making the PR, or needs to be taken note of while reviewing the PR. Ignore if none.

### CODE REVIEW

**Comment by sreeharianilkumar1** [comment]
### Why are the checks failing?

**Fixed Console Errors on Registration Page**

All the errors shown below is fixed
register

**Fixed Console Errors on Login Page**

All the errors shown below is fixed
login

**Fixed Console Errors on Code Of Conduct Page**

All the errors shown below is fixed
codeofconduct

Please help @gauravdas014

**Comment by sreeharianilkumar1** [comment]
Hi @gauravdas014, The problem I'm facing is with the 'yarn build' command, I have found a solution on Youtube. Could you please have a look into it https://www.youtube.com/watch?v=i8jkGjIIHo8

**Comment by gauravdas014** [comment]
@sreeharianilkumar1 According to the screenshot that you have attached, the problem is that you have not passed the required value in `Link`, but it's required. See the error in the console properly and please make the corrections. The checks are failing because some errors are there in the console. Once the errors are removed from the console, the checks will pass.

**Comment by sreeharianilkumar1** [comment]
> @sreeharianilkumar1 According to the screenshot that you have attached, the problem is that you have not passed the required value in `Link`, but it's required. See the error in the console properly and please make the corrections. The checks are failing because some errors are there in the console. Once the errors are removed from the console, the checks will pass.

The screenshot given is before fixing the errors. Now, none of those errors exists. The problem I'm facing is with the 'yarn build' command, I have found a solution on Youtube. Could you please have a look into it https://www.youtube.com/watch?v=i8jkGjIIHo8

**Comment by salil-naik** [comment]
> > @sreeharianilkumar1 According to the screenshot that you have attached, the problem is that you have not passed the required value in `Link`, but it's required. See the error in the console properly and please make the corrections. The checks are failing because some errors are there in the console. Once the errors are removed from the console, the checks will pass.
> 
> The screenshot given is before fixing the errors. Now, none of those errors exists. I have fixed all the errors. The problem I'm facing is with the 'yarn build' command, I have found a solution on Youtube. Could you please have a look into it https://www.youtube.com/watch?v=i8jkGjIIHo8
> 
> @salil-naik
> 
> Netlify Deploy Log
> 
> Capture

@pkspyder007 Please check why the build is failing.

**Comment by sreeharianilkumar1** [comment]
@pkspyder007 The build is failing, please help

**Pull request closed without merging**
