### PR TITLE
Feat: Use http-only cookie for jwt token (issue#168)

### LINKED ISSUE #168: Use http-only cookie for jwt token
The current implementation of JWT lets the frontend to manage the JWT token on the client-side, which can store jwt in localStorage, etc.
This could be a security issue.
To tackle this, the backend API should attach the JWT token to an HTTP-only cookie so that the frontend or any other client-side js is not able to extract the token

### PR DESCRIPTION
**Pull request by jhasuraj01**
### Fixes #168  

**Description** <br/>
Setting Secure Cookie in place of sending secure token to client javascript

### CODE REVIEW

**Comment by jhasuraj01** [comment]
@gauravdas014 Please Check this and lemme know for any necessary changes

**Comment by gauravdas014** [comment]
@jhasuraj01 make sure
1) All checks are passing
2) Please follow contributing guide and follow the specific type of commit messages that we use.
Eg: `chore: set cookie`.It's explained in the contributing guide.

**Comment by jhasuraj01** [comment]
@gauravdas014 Please check now

**Comment by pkspyder007** [comment]
@jhasuraj01 I think we would need a middleware that can validate the cookie before accessing a protected route.
You can open an issue for that if you want and I can assign it to use.

**Comment by jhasuraj01** [comment]
> 
> 
> @jhasuraj01 I think we would need a middleware that can validate the cookie before accessing a protected route.
> You can open an issue for that if you want and I can assign it to use.

@pkspyder007  Shall I create a new issue or you want me to make necessary changes in this PR only?

**Comment by pkspyder007** [comment]
Sry @jhasuraj01 for the late reply, I think you can create a new issue for that middleware part and Gaurav will review the backend PR

**Review by gauravdas014 — APPROVED** [review]

**Pull request merged**
