### PR TITLE
done API Testing for auth endpoint

### LINKED ISSUE #254: Tests for APIs are missing
Hello, 
The tests for various api endpoints are missing currently.
Since there are a lot of endpoints, it'd be better if they are broken into separate issues - one for each
- user
- story
- project
- org
- forum
- auth
- admin

I am willing to work on this issue myself.

### PR DESCRIPTION
**Pull request by subhangi2731**
### Fixes #254 

**Description** <br/>
Done API Testing for auth endpoint

### CODE REVIEW

**Comment by subhangi2731** [comment]
@gauravdas014 please create separate issues for different endpoints testing as just for auth endpoint testing it took me almost 2 weeks to complete this and I have invested a lot of time in this each endpoint testing is a level 3 issue so I would request u please assign me separate issues on the other endpoints testing. U can just see in this issue itself the code for just auth endpoint is very huge and has 2 files. please consider my request

**Comment by subhangi2731** [comment]
this is a very tough issue

**Comment by subhangi2731** [comment]
@singhayushh even u agree with me right as u have created u can understand there should be separate issue for each endpoint testing as each endpoint testing is a huge and tough one and needs lot of time for each one

**Comment by singhayushh** [comment]
> @singhayushh even u agree with me right as u have created u can understand there should be separate issue for each endpoint testing as each endpoint testing is a huge and tough one and needs lot of time for each one

Yeah, but dont just check for 200 status response and message = success. You need to test whether the api is able to create / read / update / delete resources as well

**Pull request merged**
