### PR TITLE
Feat: Validate cookies before accessing protected routes

### LINKED ISSUE #294: Feat: Validate cookies before accessing protected routes
### **Problem**
Cookies are not validated before accessing the protected path

### **Solution**
Create a Middleware which will validate the cookies first with each request coming to ```/api/secure/*``` before giving access to private routes
```javascript
app.use('/api/auth', authRouter);
app.use('/api/secure/story', storyRouter);
app.use('/api/secure/org', orgRouter);
app.use('/api/secure/admin', adminRouter);
app.use('/api/secure/user', userRouter);
app.use('/api/secure/project', projectRouter);
app.use('/api/secure/forum', forumRouter);
```

### **Additional context**
I am a GSSoC participant and I would like to work on this issue

### PR DESCRIPTION
**Pull request by jhasuraj01**
### Fixes #294

**Description** <br/>
 - Included ```cookie-parser``` module
 - Created Middleware Function to validate Cookie

### CODE REVIEW

**Comment by jhasuraj01** [comment]
@gauravdas014 please help me find the error, why this tests are failing

**Comment by gauravdas014** [comment]
@jhasuraj01 We are using `yarn` and maybe by mistake you have done `npm i <package_name>`. So a package-lock.json was generated. Remove it

**Comment by gauravdas014** [comment]
@jhasuraj01 make sure you run `yarn` once before commiting

**Comment by jhasuraj01** [comment]
> @jhasuraj01 make sure you run `yarn` once before commiting

Yes I am doing

**Comment by jhasuraj01** [comment]
@gauravdas014  please review now

**Comment by gauravdas014** [comment]
@jhasuraj01 move validate cookie function to authController. 
Also, squash the commit messages to a single one. Refer [here](https://stackoverflow.com/questions/35703556/what-does-it-mean-to-squash-commits-in-git) for squashing

**Comment by jhasuraj01** [comment]
@gauravdas014 I am unable to squash!!

**Comment by gauravdas014** [comment]
> @gauravdas014 I am unable to squash, please help!!

https://levelup.gitconnected.com/how-to-squash-git-commits-9a095c1bc1fc @jhasuraj01 please go through this. If you don't understand do let me know

**Comment by gauravdas014** [comment]
@jhasuraj01 Please resolve the merge conflict

**Comment by gauravdas014** [comment]
@jhasuraj01 Regarding squashing, leave it if you are getting difficulty. I will do that from my end. Just learn it, it will be anyways required in the future,

**Comment by jhasuraj01** [comment]
@gauravdas014  I got the concept of Rebasing but I am unable to do the same due to some conflict.

Here I donno, how to save so I edited and closed the terminal
image

and then restarted with ```git rebase --continue``` and then this conflict comes
image

Then I solved the conflicts and again try ```git rebase --continue``` and again there is a new error 😥
image

**Comment by jhasuraj01** [comment]
@gauravdas014 there is some conflict with the ```backend/package-lock.json``` file which I am unable to resolve as the resolve conflict button is disabled

image

**Comment by jhasuraj01** [comment]
I am not getting, what is the problem with ```package-lock.json```!!! 🙄

**Comment by gauravdas014** [comment]
@jhasuraj01 Let me clarify one thing. `npm` and `yarn` both are package managers. They both are used to install 3rd party packages. When we do `npm install <package-name>` a package-lock.json file is generated. And when we do `yarn add <package-name>` a yarn.lock file is generated. In our project, we are using yarn. So you should never do `npm install package-name` else we will have two lock files which are `package-lock.json` and `yarn.lock` which creates trouble. For solving the issue, simply delete package-lock.json and yarn.lock. Then do `yarn`. You will see only one lock file after these steps which is yarn.lock. Then commit the changes and force push.

**Comment by gauravdas014** [comment]
@jhasuraj01 Please add `package-lock.json` in .gitignore so that no one commits this file by mistake

**Comment by jhasuraj01** [comment]
@gauravdas014 I have already deleted the ```package-lock.json``` but this file is present in master of feminist-bible-phase-2  and hence there is a conflict with it.

**Comment by gauravdas014** [comment]
> @gauravdas014 I have already deleted the `package-lock.json` but this file is present in master of feminist-bible-phase-2 and hence there is a conflict with it.

Let me check

**Comment by jhasuraj01** [comment]
@gauravdas014  I have added ```package-lock.json``` to gitignore

**Comment by gauravdas014** [comment]
@jhasuraj01 Sorry for the inconvenience caused. The issue is resolved now.

**Comment by gauravdas014** [comment]
@jhasuraj01 Can you work on writing tests for the API?

**Comment by jhasuraj01** [comment]
@gauravdas014 please add gssoc and level labels

**Comment by jhasuraj01** [comment]
> @jhasuraj01 Can you work on writing tests for the API?

I was looking for the same 😀

**Comment by gauravdas014** [comment]
> > @jhasuraj01 Can you work on writing tests for the API?
> 
> I was looking for the same

Create corresponding issues and I will assign that

**Comment by jhasuraj01** [comment]
@gauravdas014 there is already an issue regarding api testing I will comment there

**Pull request merged**
