### PR TITLE
feat: Make Navbar sticky.

### LINKED ISSUE #208: Sticky navbar.
I want to fix the top navbar. Please assign me.

### PR DESCRIPTION
**Pull request by ManuGupta9780**
### Fixes #208 

**Description** <br/>
Made the Navbar sticky.

Steps:
1. Fixed the position of the header at the top of the page.
2. Added padding at the top equal to the height of the header so as to avoid any webpage element being hidden behind the header.

**Screenshots** <br/>
Screenshot (181)

**Addition Information (if any)** <br/>
none

### CODE REVIEW

**Comment by ManuGupta9780** [comment]
@gauravdas014 I have made the necessary changes to make the navbar sticky. Kindly review it.

**Comment by gauravdas014** [comment]
@ManuGupta9780 please follow the contributing guidelines for the type of commit messages we accept. Please change them accordingly. @pkspyder007 please review the code and merge it once the commit messages are correctly formatted

**Comment by ManuGupta9780** [comment]
Changed the commit messages.
@gauravdas014

**Comment by gauravdas014** [comment]
> Changed the commit messages.
> @gauravdas014

Please imperative sentences. Like, add padding.

**Comment by ManuGupta9780** [comment]
Please tell if any more changes are required.

**Comment by pkspyder007** [comment]
@ManuGupta9780 I will check the PR and let you know if any changes are required.

**Comment by shashankmotruri** [comment]
@ManuGupta9780  Do double check other nav pages. Add z-index. 
Screenshot (2)

**Comment by ManuGupta9780** [comment]
Added z-index.
I apologize for not checking earlier. Missed it by mistake.

**Pull request merged**
