### PR TITLE
FrontEnd : fixed #211

### LINKED ISSUE #211: fix Footer Navigation Error!! 🚀🚀
@pkspyder007 If We press the Button in Footer it actually navigates to particular url  http://localhost:3000/placeholder  , 

https://user-images.githubusercontent.com/55022929/110803080-d71a3b00-82a4-11eb-83e2-8f534c089f05.mp4

### PR DESCRIPTION
**Pull request by bhubesh757**
### Fixes #<ISSUE_NUMBER> 
#211 
**Description** <br/>
Include a summary of the change and the steps taken to make the change.

**Screenshots** <br/>
Add screenshots displaying the change.(Especially if working on UI)

https://user-images.githubusercontent.com/55022929/111017324-c5d24b00-83d8-11eb-972e-ee77b5c4ab51.mp4

**Addition Information (if any)** <br/>
Mention any additional information that has been taken note of while making the PR, or needs to be taken note of while reviewing the PR. Ignore if none.

### CODE REVIEW

**Comment by pkspyder007** [comment]
@bhubesh757 why didn't you used the <Link /> component rather than anchor tags?

**Comment by bhubesh757** [comment]
@pkspyder007 tags made the work easy bro , If we change the components it will leads another issue in anoother pages, this wont disturb at any time

**Comment by pkspyder007** [comment]
@bhubesh757 remove anchor tag and use Link component from react-router-dom

**Comment by bhubesh757** [comment]
@pkspyder007 ok

**Comment by bhubesh757** [comment]
@pkspyder007 Admin Actually , I gave only path no need to use react-router-dom , react router is already exist in app.js , so i just taken only the path , if i use the react router in footer , the code looks vulgur , the level is 1 assign , the issue is fixed , you can also check the video i shared !

**Comment by pkspyder007** [comment]
Closing due to redundant changes already fixed in other PR

**Pull request closed without merging**
