### PR TITLE
Added DeepSource Static Code Analysis

### PR DESCRIPTION
**Pull request by HarshCasper**
## Description 

I ran a DeepSource Analysis on my fork of this repository. You can see all the issues raised by DeepSource [here](https://deepsource.io/gh/HarshCasper/feminist-bible-phase-2/).

DeepSource helps you to automatically find and fix issues in your code during code reviews. This tool looks for anti-patterns, bug risks, performance problems, and raises issues. There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.

If you want to setup DeepSource for Continuous Analysis, I can help you set that up. The `.deepsource.toml` file will help you analyze your commits and pull requests every time and show blocking issues, bugs and anti-patterns.

### CODE REVIEW

**Comment by HarshCasper** [comment]
cc: @gauravdas014 @salil-naik

**Comment by gauravdas014** [comment]
@HarshCasper there are two apps inside the repo, one is react app and another one is the node app. Will one config file for deepspurce handle both of them?

**Comment by HarshCasper** [comment]
Hi @gauravdas014 

Thanks for the review! I have added the dependency file paths to take into account the Frontend and Backend Directories and also added some meta analyzers to ensure that the ES6 is followed and the `es-modules` is being used.

**Comment by gauravdas014** [comment]
> Hi @gauravdas014
> 
> Thanks for the review! I have added the dependency file paths to take into account the Frontend and Backend Directories and also added some meta analyzers to ensure that the ES6 is followed and the `es-modules` is being used.

Looks good to me. Thank you for the PR @HarshCasper

**Pull request merged**
