### PR TITLE
Create story post

### LINKED ISSUE #29: Add create story controller function
Under controllers directory in userController create a function to create a story . (It's for the scenario when users will write some story (post) ). Add a route and link this to the controller function. Please attach a screenshot of the response in the PR ( Test in postman)

### PR DESCRIPTION
**Pull request by pratikbaid3**
### Fixes #29 

**Description** <br/>
Completed the controller for creating a story and also created a route for it (/api/story/create)

**Screenshots** <br/>
Screenshot 2020-09-26 at 2 04 02 PM

### CODE REVIEW

**Comment by gauravdas014** [comment]
use ===  or  !== wherever necessary , == creates a lot of problem

**Comment by pratikbaid3** [comment]
Ok will fix it and make another PR

**Comment by gauravdas014** [comment]
if you need to check if something is undefined inside if else directly use as following

if(story) {  // here if statement will work only if story is not undefined. Use similarly. 
} 
In the response code of catch use 400 as it's  used for bad requests.

**Comment by pratikbaid3** [comment]
Fixed

**Comment by pratikbaid3** [comment]
Fixed

**Pull request merged**
