### PR TITLE
Update Footer.jsx

### PR DESCRIPTION
**Pull request by bhubesh757**
### Fixes #<ISSUE_NUMBER> 
#211 
**Description** <br/>
Include a summary of the change and the steps taken to make the change.

**Screenshots** <br/>
Add screenshots displaying the change.(Especially if working on UI)

https://user-images.githubusercontent.com/55022929/111017324-c5d24b00-83d8-11eb-972e-ee77b5c4ab51.mp4

**Addition Information (if any)** <br/>
Mention any additional information that has been taken note of while making the PR, or needs to be taken note of while reviewing the PR. Ignore if none.

### CODE REVIEW

**Comment by gauravdas014** [comment]
@pkspyder007 please review it. @bhubesh757 why are the checks failing? Please have a look.

**Comment by bhubesh757** [comment]
@gauravdas014 its failing tell me the solution

**Comment by bhubesh757** [comment]
> @pkspyder007 please review it. @bhubesh757 why are the checks failing? Please have a look.
@gauravdas014 @pkspyder007 code and everything is fine it works on my localhost , please check this and give me a solution

**Comment by pkspyder007** [comment]
@bhubesh757 The reason why this is failing because you have imported the Link component and never used it in the code.
+ Why you are wrapping Navlink with BrowserRouter.

For simply creating link with react-router-dom we use <Link to="/organisations">Organisations</Link>
No need of adding unnecessary stuff keep it simple

If you to learn goto this link 
https://reactrouter.com/web/guides/quick-start

**Comment by pkspyder007** [comment]
@bhubesh757 Looks good hope you learned about using react-router-dom.

**Pull request merged**
