### PR TITLE
🚀 Chores: Update ISSUE_TEMPLATES for contribution bug and feature request.

### LINKED ISSUE #212: chore(update): missing bug_report and feature request template
**Need**?

- Important according to OSS guidelines.
- Help maintainer to differentiate a `bug` `feature`, `feature(already included in the project)`

Hey Maintainer!
I want to work on creating an effective template for bug and feature requests.
Please assign me the task. (**For GGSOC'21**)

### PR DESCRIPTION
**Pull request by Uyadav207**
Fixes #212  

**Description**

- Bug and feature reports are important and an essential part of OSS projects.

**Screenshots**

- Not required.

**Addition Information (if any)**

- Added `bug_report.md`
- Added `feature_request.md`

### CODE REVIEW

**Comment by Uyadav207** [comment]
@gauravdas014,  please review it.

**Comment by pkspyder007** [comment]
Looks good to me 👍

**Comment by gauravdas014** [comment]
@Uyadav207 Please give the PR to the develop branch. It's written in the contributing guideline that pr is to be given in the develop branch. Otherwise, it looks fine to me.

**Comment by Uyadav207** [comment]
> @Uyadav207 Please give the PR to the develop branch from next time. It's written in the contributing guideline that pr is to be given in the develop branch. Otherwise, it looks fine to me. I am changing the base branch from my end.

Ok i will remember it. I usually do that might got skipped.... Thanks for your help ...

**Comment by Uyadav207** [comment]
@gauravdas014, Is there any problem with score board... anu bug ??

**Comment by gauravdas014** [comment]
@Uyadav207 please ask in the general section of the discord server.

**Comment by Uyadav207** [comment]
image

Just to clarify @gauravdas014 is it not because .... tags have been updated... can please check and confirm?

This would be a big help. 🤗

**Comment by gauravdas014** [comment]
What's the issue you are facing? @Uyadav207

**Comment by Uyadav207** [comment]
Earlier: my leaderboard after contribution
- PR: 1
- issue: 1
- Commit : 0
- Projects: 0
- score: 0

But now at this moment

- PR: 1
- issue: 1
- commit: 0
- Project: 0
- Score: 10 (Only this got updated after you put the Tags)

**Comment by Uyadav207** [comment]
SO I want to know if the tag for gsoc21 is `GGSOC21` or `ggsoc21`

**Comment by gauravdas014** [comment]
It's GSSOC21 or gssoc21. Case-insensitive

**Comment by Uyadav207** [comment]
ok got it ... So it's the website bug that they are not showing contributions.... fetching of data problem I guess...

**Comment by gauravdas014** [comment]
> ok got it ... So it's the website bug that they are not showing contributions.... fetching of data problem I guess...

Maybe. Please ask in the general section of discord regarding these issues. Someone would definitely help you out.

**Pull request merged**
