### PR TITLE
Single story

### LINKED ISSUE #31: Add get a single story controller function
Add a controller function to get a single story. Attach response from postman in the pr.

### PR DESCRIPTION
**Pull request by ruchikamuddinagiri**
Closes #31
Postman screenshot added here:
image

### CODE REVIEW

**Comment by gauravdas014** [comment]
on the description write as   closes #31 .
Use 400 code instead of 404 and 500. These status code rules are not hard and fast, but we should have some uniformity in the code.

**Comment by ruchikamuddinagiri** [comment]
Done!

**Comment by gauravdas014** [comment]
Please change the route name from getStory to story

**Comment by ruchikamuddinagiri** [comment]
The current route is  /api/story/getStory.
Please confirm whether I should change this to /api/story/story
maybe we can change it to /api/story/single.

**Comment by gauravdas014** [comment]
Please pass the id as a parameter. So the route will be api/story/:storyId      . So it will be only  "/:storyId"

**Comment by ruchikamuddinagiri** [comment]
Route changed and id passed as parameter. Postman screenshot attached here:
image

**Comment by gauravdas014** [comment]
The changes looks fine now. Please try to resolve the merge conflict. Ping me if you aren't able to resolve it

**Pull request merged**
