### PR TITLE
updated contributing.md

### LINKED ISSUE #209: Make Changes in contributing.md
Hi @salil-naik @gauravdas014 @pkspyder007  I would like to make changes and update contributing.md . I will mention steps on how to clone a repo and install on local system ,how to make a branch and use git commands to push it to origin ,How to make a PR , how to update your forkedrepo as well as local repo as the changes are made to the upstream

I would like to work on it as a part of GSSOC'21

### PR DESCRIPTION
**Pull request by khareyash05**
###  #209  

docs: update contributing guide

### CODE REVIEW

**Comment by gauravdas014** [comment]
@khareyash05 Please refer to commit message formats in the contributing guideline

**Comment by gauravdas014** [comment]
@khareyash05 Do not use too many &nbsp; for alignment. Align by wrapping the image in HTML tags

**Comment by khareyash05** [comment]
> @khareyash05 Please refer to commit message formats in the contributing guideline

Removed Fixes and Added Chore

**Comment by khareyash05** [comment]
> @khareyash05 Do not use too many `&nbsp;` for alignment. Align by wrapping the image in HTML tags

Sure! I will look into that

**Comment by gauravdas014** [comment]
@khareyash05 Please update the commit message to `docs: update contributing guide` . We are following a standard for writing commit messages. Please ask if you still have any doubt.

**Comment by khareyash05** [comment]
Used HTML tag to align image instead of &nbsp; @gauravdas014 have a look

**Comment by gauravdas014** [comment]
Thank you @khareyash05 for all the changes. There is something called `squashing commits` are you aware of it? It's used for combining two or more commits into a single commit. Please squash the commits.

**Comment by khareyash05** [comment]
@gauravdas014  I am sorry I dont know about it. Could you pls guide me through it

**Comment by gauravdas014** [comment]
> @gauravdas014 I am sorry I dont know about it. Could you pls guide me through it

Definitely. 
Please refer to these resources. Just search for `squashing commits` and you will find a lot of resources
https://www.git-tower.com/learn/git/faq/git-squash/
https://www.youtube.com/watch?v=V5KrD7CmO4o

**Comment by khareyash05** [comment]
@gauravdas014 will this work ? `git rebase -i HEAD~2` as I have 2 commits?

**Comment by gauravdas014** [comment]
> @gauravdas014 will this work ? `git rebase -i HEAD~2` as I have 2 commits?

Yes. The 2 means Head will point to the second last commit. Then you will get the option to delete or edit commits. Delete the wrongly formatted commit message and then you need to force push to your repo. `git push -f`

**Comment by gauravdas014** [comment]
@khareyash05 Please give your PR to the dev branch.

**Comment by khareyash05** [comment]
@gauravdas014 Have a look Am I done with all the changes you wanted

**Comment by gauravdas014** [comment]
> @gauravdas014 Have a look Am I done with all the changes you wanted

It still showing 2 commits. As it is your first contribution, I can squash from my side also. Would you want me to do that?

**Comment by khareyash05** [comment]
@gauravdas014 I would be highly grateful if you could do the same Thank you very much

**Comment by khareyash05** [comment]
I am actually a bit confused in this ...I will learn this and will squash on my own from the next PR

**Comment by gauravdas014** [comment]
> @gauravdas014 I would be highly grateful if you could do the same Thank you very much

No problem. Just make sure you learn squashing, it will be useful in the future too. I know I have asked you to make too many changes in your very first pr, but that's how we learn. Open source is all about contributing, learning new things and also following the standards which the repo is maintaining. Good work @khareyash05

**Comment by gauravdas014** [comment]
> I am actually a bit confused in this ...I will learn this and will squash on my own from the next PR

Definitely, no issue at all. Whenever you need any help feel free to ask. The open-source community is generous enough.

**Comment by khareyash05** [comment]
Thank You @gauravdas014 . Do I have to make any more changes to the same?

**Comment by gauravdas014** [comment]
> Thank You @gauravdas014 . Do I have to make any more changes to the same?

No. All changes have been made. Thank you and Good luck with your open source journey.

**Comment by khareyash05** [comment]
@gauravdas014 May I know this issue is under which label in GSSOC'21

**Comment by khareyash05** [comment]
> Level1

Could you please add a GSSOC label to the issue?

**Comment by pkspyder007** [comment]
@khareyash05 The issue that corresponds to this PR i.e. #209 already had a gssoc21 label to it. 👍

**Comment by khareyash05** [comment]
@gauravdas014 @pkspyder007  Could you pls add a level label and a GSSOC label to the PR as well because adding a level label to the PR is only being counted
Thanx!

**Pull request merged**
