### PR TITLE
Added User Schema

### LINKED ISSUE #10: Create a user schema
It should have the basic things of user , eg: Name, email, phone, password. Other things will be added later on

### PR DESCRIPTION
**Pull request by Shubham-1105**
close #10

### CODE REVIEW

**Comment by gauravdas014** [comment]
2 points:
1. Use const for requiring mongoose
2. Please remove the password encryption part for now. We will probably be using bcrypt js for that. We will decide it later on.

**Comment by gauravdas014** [comment]
Please use const instead of var in line no 3. Const should be used as we need to define the schema once only

**Comment by Shubham-1105** [comment]
Done @gauravdas014 .Close #10

**Comment by gauravdas014** [comment]
Looks fine now!

**Pull request merged**
