### PR TITLE
admin and user schema added

### PR DESCRIPTION
**Pull request by nanda-mik**
close issue #10 and #11

### CODE REVIEW

**Comment by gauravdas014** [comment]
You have written 2 mongoose in line no 23, please correct it @nanda-mik

**Comment by gauravdas014** [comment]
Please mention close #issue_no at the description

**Comment by nanda-mik** [comment]
issue #10 and issue #11

**Comment by gauravdas014** [comment]
You were not assigned this task. So I will be closing your PR. Don't do this from next time. Please give PR for only those issues that you are assigned.

**Pull request closed without merging**
