### PR TITLE
fixes deleteController and isSigned Controller

### LINKED ISSUE #91: IsLogged in
Make a controller function under authController to check if a user is logged in.

### PR DESCRIPTION
**Pull request by Shubham-1105**
closes #91

### CODE REVIEW

**Comment by gauravdas014** [comment]
We aren't using passport. Don't use passport.

**Comment by Shubham-1105** [comment]
Then we have to read the token using expressJWT?

**Comment by gauravdas014** [comment]
yes!

**Comment by Shubham-1105** [comment]
fixed it ,any changes required ? closes #91

**Comment by gauravdas014** [comment]
No

**Pull request merged**
